### ISSUE TITLE
Not able to run semanage-<command>

### ISSUE THREAD

**Issue by mgrepl** [bachradsusi/build-selinuxproject-rpms#1]
# semanage permissive -l

Traceback (most recent call last):
  File "/sbin/semanage", line 32, in <module>
    import seobject
  File "/usr/lib/python3.5/site-packages/seobject/**init**.py", line 26, in <module>
    import selinux
  File "/usr/lib64/python3.5/site-packages/selinux/**init**.py", line 28, in <module>
    _selinux = swig_import_helper()
  File "/usr/lib64/python3.5/site-packages/selinux/__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_selinux', fp, pathname, description)
  File "/usr/lib64/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/python3.5/site-packages/selinux/_selinux.so: undefined symbol: selabel_partial_match

**Comment by mgrepl** [comment]
```
# rpm -qa libselinux-* libsepol-* policycoreutils-* setools-*
libselinux-python3-2.5-0.2.a2a3c6d.fc24.x86_64
policycoreutils-devel-2.5-0.4.gita2a3c6d.fc24.x86_64
policycoreutils-sandbox-2.5-0.4.gita2a3c6d.fc24.x86_64
libselinux-static-2.5-0.2.a2a3c6d.fc24.x86_64
setools-console-3.3.8-8.2.fc24.f1e5b20.x86_64
policycoreutils-gui-2.5-0.4.gita2a3c6d.fc24.x86_64
libsepol-devel-2.5-0.2.gita2a3c6d.fc24.x86_64
setools-libs-3.3.8-8.2.fc24.f1e5b20.x86_64
libselinux-python-2.5-0.2.a2a3c6d.fc24.x86_64
policycoreutils-python3-2.5-0.4.gita2a3c6d.fc24.x86_64
libselinux-debuginfo-2.5-0.2.a2a3c6d.fc24.x86_64
policycoreutils-python-2.5-0.4.gita2a3c6d.fc24.x86_64
policycoreutils-newrole-2.5-0.4.gita2a3c6d.fc24.x86_64
libsepol-static-2.5-0.2.gita2a3c6d.fc24.x86_64
setools-devel-3.3.8-8.2.fc24.f1e5b20.x86_64
libsepol-debuginfo-2.5-0.2.gita2a3c6d.fc24.x86_64
libselinux-devel-2.5-0.2.a2a3c6d.fc24.x86_64
libselinux-utils-2.5-0.2.a2a3c6d.fc24.x86_64
policycoreutils-python-utils-2.5-0.4.gita2a3c6d.fc24.x86_64
```

**Comment by bachradsusi** [comment]
Fixed on the reporter's system.

**Comment by shobhitagarwal1612** [comment]
How was this fixed? Struggling with the same issue.

**Comment by bachradsusi** [comment]
At one point, `_selinux.so`  was moved from `$(PYLIBDIR)/site-packages/selinux/`  to `$(PYLIBDIR)/site-packages/` and IIRC the reporter had both files and the old one was used.
